.\" $Id$
.TH ocr-learn 1 "May 1, 2009" "CS 315" "Sonoma State University"
.SH NAME
ocr-learn \- create font data files
.SH SYNOPSIS
.B ocr-learn
font image[...]
.SH DESCRIPTION
The
.B ocr-learn
program generates font data files for the
.B ocr
program. The operands consist of a
.I font
name for data storage, followed by the filenames of any number of BMP
.I images
as samples of the font.
.P
Each image must contain the same characters in the same order, and in the desired font. The characters in the images must be the following string, or any initial part of it.
.RS
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,?!/@_
.RE
.SH EXAMPLES
Generate data for the FreeSans font using samples in a variety of sizes:
.RS
ocr-learn freesans freesans36.bmp freesans48.bmp freesans72.bmp
.RE
.SH FILES
Font information is stored in files in the
.I font
directory in the same directory as the executable. These files have the suffix
.I .font
.P
Font data files can be used with the
.B ocr
program.
.SH AUTHOR
Corey Ford <fordco@sonoma.edu>
